package cn.itcast.ssm.mapper;

import cn.itcast.ssm.po.Discuss;
import cn.itcast.ssm.po.DiscussExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int countByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int deleteByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int insert(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int insertSelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    List<Discuss> selectByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    Discuss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int updateByExample(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int updateByPrimaryKeySelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    int updateByPrimaryKey(Discuss record);
}