package cn.itcast.ssm.po;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.details
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.discussid
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    private Integer discussid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.details
     *
     * @return the value of reply.details
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.details
     *
     * @param details the value for reply.details
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.discussid
     *
     * @return the value of reply.discussid
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public Integer getDiscussid() {
        return discussid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.discussid
     *
     * @param discussid the value for reply.discussid
     *
     * @mbggenerated Sun Apr 29 19:11:51 CST 2018
     */
    public void setDiscussid(Integer discussid) {
        this.discussid = discussid;
    }
}